slick.dbs.default.profile = "slick.jdbc.PostgresProfile$"
slick.dbs.default.db.driver = "org.postgresql.Driver"

slick.dbs.default.db.url = "jdbc:postgresql://localhost:5432/streamforge"
slick.dbs.default.db.user = "dharanisham"
slick.dbs.default.db.password = ""

play.http.secret.key = "dev-only-change-me"

play.evolutions.enabled = false
play.modules.disabled += "play.api.db.evolutions.EvolutionsModule"
play.modules.enabled += "modules.FlywayModule"

flyway.enabled = true
flyway.url = ${slick.dbs.default.db.url}
flyway.user = ${slick.dbs.default.db.user}
flyway.password = ${slick.dbs.default.db.password}
flyway.locations = ["classpath:db/migration"]
flyway.baselineOnMigrate = true

play.filters.disabled += play.filters.csrf.CSRFFilter
play.filters.hosts.allowed = ["."]
play.filters.enabled += "filters.RequestLoggingFilter"
